name: test pull-request
run-name: ${{ gitea.actor }} is testing out pull-request 🚀
on: [pull_request]

jobs:
  test-pull-request:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "the job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "this job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "the name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - setup-pipes:
          - name: checkout repository code
            uses: actions/checkout@v3
          - name: install dependencies
            env:
              SKIP_POSTINSTALL: 1
            run: yarn install
          - name: lint client with eslint
            run: yarn lint:next
          - name: lint server with eslint
            run: yarn lint:nest
          - name: lint server with typescript
            run: yarn lint:ts:nest
      - setup-pipes:
          - name: update build version files
            uses: actions/update-version@v3
      - setup-pipes:
          - name: test backend startup
            uses: actions/test-backend-startup@v3
      - setup-pipes:
          - name : test frontend startup
            uses : actions/test-frontend-startup@v3
      - setup-pipes :
          - name : test if anything is dirty after backend and frontend startup
            uses : actions/test-dirty-check@v3
      - run : echo "this job status is ${{ job.status }}."
